### ISSUE TITLE
<Home /> component

### ISSUE THREAD

**Issue by andferguson** [BAM-Shopper/BAM-Shopper#10]
As a visitor, I want the home page to have all the products, so that I can choose one to see more detailed information.

- [x] `<Home />` component contains `<SideBar />` and `<ProductList />` components
- [x] `<ProductList />` component has a `products` prop passed into it 
- [x] a callback will be passed to `<SideBar />`, which will filter a list of rendered products saved to the `<Home />` component's local state, which is then passed to `<ProductList />` as a prop
- [x]  `<Route exact path="/" component={Home} />`
- [x] Tests

**Comment by maddieeiddam** [comment]
i'm calling the prop passed to ProductList 'products' instead of list
